### PR TITLE
jakarta namespace

### PR DESCRIPTION
**Pull request by rsearls**
Update plugin to support jakarta native API.

### CODE REVIEW

**Comment by mattrpav** [comment]
@rsearls does this PR pass all the tests with the -Pall profile enabled?

**Comment by rsearls** [comment]
No, I did not know to test with -Pall.  However the project using this plugin has since replaced it with a different plugin, so the issue is a moot point for me.

**Comment by mattrpav** [comment]
@rsearls understood, thank you for the prompt reply.

**Comment by zjedi** [comment]
@mattrpav What is missing for this PR to be merged?
This is still and issues for https://github.com/esig/dss/pull/165 and others

**Comment by laurentschoelens** [comment]
@zjedi since major refactot as been done on this repository, this PR will be closed unmerged
But the good news is : we are currently working on jakarta migration and jaxb v3 support should come very shortly

**Comment by zjedi** [comment]
@laurentschoelens thanks, is there any other branch / PR I can watch instead?

**Comment by laurentschoelens** [comment]
> @laurentschoelens thanks, is there any other branch / PR I can watch instead?

We are curently working on 2.0.5 version containing annox and annotate plugins
After this, we (Matt or myself) will cut off v2 branch, move master / main to 3.0.0 snapshot and provide PR to support jakarta jaxb v3.

I'll mention this new PR in this one if you like here

**Comment by laurentschoelens** [comment]
I'll also close https://github.com/highsource/jaxb-tools/pull/255 when the new PR will be provided by mentionning it there too

**Pull request closed without merging**
