### PR TITLE
update README

### PR DESCRIPTION
**Pull request by soc**
- replace outdated links
- drop obsolete parts
- adjust wording
- add information on v3

### CODE REVIEW

**Comment by laurentschoelens** [comment]
@soc  thanks for your contribution.

Could you adapt with the following changes ? 

- I would point to new location of [jaxb-api](https://github.com/jakartaee/jaxb-api)  / [jaxb-ri](https://github.com/eclipse-ee4j/jaxb-ri) github places
- I wouldn't remove the note about [mojohaus maven-plugin](https://github.com/mojohaus/jaxb2-maven-plugin)

Thanks

**Comment by soc** [comment]
> I would point to new location of [jaxb-api](https://github.com/jakartaee/jaxb-api) / [jaxb-ri](https://github.com/eclipse-ee4j/jaxb-ri) github places

I feared it would be confusing to link to v3 resources while the plugin only supports v2, but will do!

> I wouldn't remove the note about [mojohaus maven-plugin](https://github.com/mojohaus/jaxb2-maven-plugin)

I dropped it because I figured if we can't explain what it is and how it differs from this project, then it will not be helpful to readers either.
Do you have some additional info we can add there?

**Comment by laurentschoelens** [comment]
> > I would point to new location of [jaxb-api](https://github.com/jakartaee/jaxb-api) / [jaxb-ri](https://github.com/eclipse-ee4j/jaxb-ri) github places
> 
> I feared it would be confusing to link to v3 resources while the plugin only supports v2, but will do!
> 

There's no active branches for jaxb-api v2 / v3 but the latest release are in the new location (https://github.com/jakartaee/jaxb-api/tree/2.3.3)
For jaxb-ri, the [EE8](https://github.com/eclipse-ee4j/jaxb-ri/tree/EE8) branch points to jaxb-api v2.3.3. 

> > I wouldn't remove the note about [mojohaus maven-plugin](https://github.com/mojohaus/jaxb2-maven-plugin)
> 
> I dropped it because I figured if we can't explain what it is and how it differs from this project, then it will not be helpful to readers either. Do you have some additional info we can add there?

Since the names or now quite identical, pointing to mojohaus' plugin would help user create the issue in the right location in my opinion.

**Comment by soc** [comment]
Pushed some changes, moved the link to JAXB to the top to avoid having two links right next to each other, better this way?

**Comment by laurentschoelens** [comment]
LGTM, I'll let @mattrpav validate before merging :)

**Review by laurentschoelens — APPROVED** [review]
LGTM, thanks

**Review by mattrpav — APPROVED** [review]
LGTM

**Pull request merged**
