### PR TITLE
Fixing JT-173 (backport of modified version of PR made by phax)

### PR DESCRIPTION
**Pull request by laurentschoelens**
Phax does this PR which doesn't break build and fixes his issue #173 
Without it, he forked the project and maintains it (with jakarta support).

### CODE REVIEW

**Comment by laurentschoelens** [comment]
Added UT for IOUtils new function.
Made some changes in initial function of phax since issues discovered while adding UT.

**Comment by mattrpav** [comment]
Do we have a jaxb-maven project to confirm it works? Seems his issue was about ordering of schemas.

**Comment by laurentschoelens** [comment]
> Do we have a jaxb-maven project to confirm it works? Seems his issue was about ordering of schemas.

All of existings jaxb-maven projects tests confirm that there is no regression.
This PR is also based on the original PR of phax but with better sort handling since we could have non wanted sorts items (initial PR tested path endsWith includes items path, which may me wrong).

The main goal of this PR is to have files resolution as close as includes items even if files are not returned in a consistent way across build platforms.

**Comment by mattrpav** [comment]
Do we have a test project that uses "*" to references schemas and have schemas in a non-matching folder to make sure they do _not_ get included?

User's original dynamic list (issue showed up as resolution when really wide):
```
              <schemaIncludes>
                <schemaInclude>common/*.xsd</schemaInclude>
                <schemaInclude>maindoc/*.xsd</schemaInclude>
              </schemaIncludes>
```

**Comment by laurentschoelens** [comment]
Reworked on the PR
The main point is DirectoryScanner in plexus-utils does not return files in a consistent way
So here, we do take the result of DirectoryScanner files, and reorder them strictly according to includes configuration section in the pom.

We use the same patternmatcher as plexus-utils does to check if returned file does match each include pattern in configuration order to sort them this way.
Added more UT to validate the fix.

**Review by mattrpav — APPROVED** [review]
LGTM

**Pull request merged**
