### PR TITLE
JT-176 : Bump plexus-utils / plexus-build-api

### PR DESCRIPTION
**Pull request by laurentschoelens**
See : https://github.com/highsource/jaxb-tools/issues/176

### CODE REVIEW

**Comment by laurentschoelens** [comment]
Same as https://github.com/highsource/jaxb-tools/pull/249 but with higher version and migration of `plexus-build-api` from sonatype:0.0.7 to codehaus:1.2.0

**Review by mattrpav — CHANGES_REQUESTED** [review]
Please refactor to put a property for the version number(s), and then update the dependency using the macro ${ .. }

<plexus-build-api.version>1.2.0</plexus-build-api.version>
<plexus-utils.version>3.5.1</plexus-utils.version>

**Comment by laurentschoelens** [comment]
> Please refactor to put a property for the version number(s), and then update the dependency using the macro ${ .. }
> 
> <plexus-build-api.version>1.2.0</plexus-build-api.version> <plexus-utils.version>3.5.1</plexus-utils.version>

- [x] Changed applied
- [x] Force push done

**Review by mattrpav — APPROVED** [review]
LGTM

**Pull request merged**
