### PR TITLE
Merging jaxb-basics / jaxb-annotate in this repository

### PR DESCRIPTION
**Pull request by laurentschoelens**
Process used described here : https://github.com/highsource/jaxb-tools/issues/264

Final commit handles the merge migration process to make all modules in one single maven build with additional work on jdk17 build failure (on basics / annotate parts) and usage of jaxb-maven-plugin in basics / annotate subprojects.

### CODE REVIEW

**Comment by laurentschoelens** [comment]
Only the last commit is interesting to review in my opinion :
https://github.com/highsource/jaxb-tools/pull/276/commits/e037ec8892d475dde476ea13f94c4c64156c32c3

**Comment by laurentschoelens** [comment]
Will close this PR when @mattrpav will end up with a more softer approach of this migration 😄 
Work in progress

**Comment by bertramn** [comment]
@laurentschoelens  and @mattrpav any way we could help with the refactoring? We need to move to JAXB 3 in the next 2 months and happy to discuss migration strategies and contribute. I had a look at the various PRs and it feels like work is getting stuck due to "too big to refactor" situation. Maybe there are some other approaches we could try.

**Comment by laurentschoelens** [comment]
> @laurentschoelens  and @mattrpav any way we could help with the refactoring? We need to move to JAXB 3 in the next 2 months and happy to discuss migration strategies and contribute. I had a look at the various PRs and it feels like work is getting stuck due to "too big to refactor" situation. Maybe there are some other approaches we could try.

Hi @bertramn 
We are working with @mattrpav in fixing various bugs that are open for a long time now.
When done and refactoring done too, we will move on to jakarta very soon.
If you need to test jaxb3 with jakarta classes, you can use this trick until official release : https://github.com/highsource/jaxb-tools/issues/233#issuecomment-1632508716
Worked for many people and also used by some collegues.
Tell us if that works for you too.

**Comment by bertramn** [comment]
The workaround in #233 would never work for our setup. Yes it changes the generated source files but it leaves all the compilation episodes and schema namespaces produced by XJC broken with old sun links. I guess what could help is a snapshot release of the update progress [1]. This way we could test provide MRs for things not working. @laurentschoelens  is there appetite to break this down and have people help get the migration finished?

[1] https://central.sonatype.org/publish/publish-maven/#performing-a-snapshot-deployment

**Pull request closed without merging**
