### PR TITLE
Fixing issue JT-194 : adding TypeArtifactFilter to exclude pom artifacts

### LINKED ISSUE #194: scanDependenciesForBindings fails on dependency of type pom
org.apache.maven.plugin.MojoExecutionException: Unable to read the artifact JAR file [D:\mvn_repo\org\jboss\spec\jboss-jakartaee-8.0\1.0.1.Final\jboss-jakartaee-8.0-1.0.1.Final.pom].

```
[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate (Config) on project ssh-gui-report: Unable to read the artifact JAR file [D:\mvn_repo\org\jboss\spec\jboss-jakartaee-8.0\1.0.1.Final\jboss-jakartaee-8.0-1.0.1.Final.pom].: zip END header not found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate (Config) on project ssh-gui-report: Unable to read the artifact JAR file [D:\mvn_repo\org\jboss\spec\jboss-jakartaee-8.0\1.0.1.Final\jboss-jakartaee-8.0-1.0.1.Final.pom].
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to read the artifact JAR file [D:\mvn_repo\org\jboss\spec\jboss-jakartaee-8.0\1.0.1.Final\jboss-jakartaee-8.0-1.0.1.Final.pom].
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.collectBindingUrisFromDependencies (RawXJC2Mojo.java:833)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.createBindingURIs (RawXJC2Mojo.java:270)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.setupBindings (RawXJC2Mojo.java:227)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute (RawXJC2Mojo.java:437)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute (RawXJC2Mojo.java:320)
```

Because I have this dependency in my project:

```
		<dependency>
			<groupId>org.jboss.spec</groupId>
			<artifactId>jboss-jakartaee-8.0</artifactId>
			<type>pom</type>
			<scope>provided</scope>
		</dependency>
```

### PR DESCRIPTION
**Pull request by laurentschoelens**
This will exclude pom artifacts in collectBindingUrisFromDependencies and so, fix #194

### CODE REVIEW

**Comment by mattrpav** [comment]
Do we have a maven project test to confirm this works outside the unit test?

**Comment by laurentschoelens** [comment]
I can add one 😄

**Review by mattrpav — CHANGES_REQUESTED** [review]
Shouldn't 'scanDependenciesForBindings' be enabled in the plugin config to verify?

**Comment by laurentschoelens** [comment]
- [x] Rebased PR from master since conflicts with latest merge
- [x] Adding `scanDependenciesForBindings` flag to `true`

- [x] Tested with 2.0.2 version of the plugin and get the following error :

```
[ERROR] Failed to execute goal org.jvnet.jaxb:jaxb-maven-plugin:2.0.2:generate (generate) on project jaxb-maven-plugin-tests-194: Unable to read the artifact JAR file [.../.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.pom].: zip END header not found -> [Help 1]
```

- [x] Tested with 2.0.4-SNAPSHOT current version, build is OK

For me, this simple `jt-194` test project validate the fix

**Comment by mattrpav** [comment]
#299 has follow-on task to validate the 'scanDependenciesForBindings' feature going forward

**Review by mattrpav — APPROVED** [review]
LGTM

**Pull request merged**
